AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Results Query para Sistema de Detecção de Frutas

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hom
      - prod
    Description: Ambiente de implantação
  
  DynamoDBTableName:
    Type: String
    Description: Nome da tabela DynamoDB de resultados
  
  S3ResultsBucket:
    Type: String
    Description: Bucket S3 para armazenamento de resultados

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO
        AWS_REGION: !Ref AWS::Region

Resources:
  ResultsQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fruit-detection-${Environment}-results-query
      CodeUri: .
      Handler: src.app.lambda_handler.lambda_handler
      Runtime: python3.13
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          S3_RESULTS_BUCKET: !Ref S3ResultsBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/*
            
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
              Resource:
                - !Sub arn:aws:s3:::${S3ResultsBucket}/*
            
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource: '*'

      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub fruit-detection-${Environment}-results-query-api
      StageName: !Ref Environment
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ResultsQueryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ResultsQueryFunction}
      RetentionInDays: 7

  ResultsQueryErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub fruit-detection-${Environment}-results-query-errors
      AlarmDescription: Dispara quando a Lambda Results Query apresenta erros
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ResultsQueryFunction

Outputs:
  ResultsQueryFunctionArn:
    Description: ARN da função Lambda Results Query
    Value: !GetAtt ResultsQueryFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ResultsQueryFunctionArn
  
  ApiGatewayUrl:
    Description: URL do endpoint API Gateway
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiGatewayUrl